### ISSUE TITLE
ruby-oci8

### ISSUE THREAD

**Issue by vgpal22** [larskanis/rubyinstaller2#11]
The gem is compiled without any errors with msys2 toolchain.
But oci8lib_240.so load error is coming when I use the gem.
Gems with pure ruby code are working fine.

**Comment by MSP-Greg** [comment]
And we complain about MSFT error messages...

I'm by no means an expert, but often with 'extension' gems this occurs when an .so file is loaded/required but it depends on a dll that Windows can't find.  One can often determine what dll is 'missing' by looking at the .so file with depends.exe / Dependency Walker, finding it in your system, then either adding the dll to Ruby/bin or adding it's location to your path.

This can be an issue with both RI and RI2, but I wouldn't consider it an error on either's part.  Build systems often modify the 'current' path during builds.  So, should those path additions be permanent or not?  On my systems, I prefer not.  Also, I don't know how things work on non-Windows systems.

I'm sure I've got some of this wrong, but it should solve your issue.  I had the same issue with Nokogiri,  libxml-ruby, and a few other gems.

**Comment by larskanis** [comment]
I'm able to reproduce this issue. To the binary gem:

Neither the x86 nor the x64 binary gem work with RI2. According to
depends.exe there are no unmet dll dependency and according to
processmonitor the dll is mapped successfully into process memory, but
fails somehow afterwards so that LoadLibrary() finally returns with
"Invalid Argument". Possibly there are unresolved symbols with the ruby
runtime dll.

I wonder how the oci8lib_240.so was build, because other binary gems like
ffi-1.9.17-x64-mingw32 or latest pg prerelease-version just work with RI2.

To the source gem:
The installation with the Oracle instant client works out of the box, if
the client is saved to a path without spaces. However it fails to load
oci8lib_240.so at runtime, because the oci.dll can't be found. This is
because RI2 separates the PATH environment variable from dll lookup. So the
PATH is used for executables only and is ignored for dlls. Instead there is
a new API in RI2 which can be used to add directories for the dll search:
https://github.com/larskanis/rubyinstaller2/blob/master/lib/ruby_installer.rb

It looks like this:
```ruby
require "ruby_installer"
RubyInstaller.add_dll_directory('c:/path')
```
This is more secure and will hopefully avoid interferences with other
(mingw/msys-based) installed programs.

I'll open a proper pull request on ruby-oci8 which adds this.

**Comment by vgpal22** [comment]
When I copied oci.dll to ruby\bin and use the gem, the following error is comming:
oci8lib.c:156:in oci8lib_240.so: OCI Library Initialization Error - D:\Programs\Ruby\bin\OCI.DLL (OCIError)

**Comment by larskanis** [comment]
It should work if you copy all dlls beneath oci.dll as well.

**Comment by vgpal22** [comment]
Copied o.* (except o.exe) to ruby\bin.
Now it is working.
Still experimenting.

**Comment by vgpal22** [comment]
Simple and easier way is: added the following lines in lib/oci8.rb.
require 'ruby_installer'
RubyInstaller.add_dll_directory( "path of oracle bin dir" )
Does not look nice, but working fine.

**Comment by larskanis** [comment]
@kubo Thanks for solving this issue in oci8! And just for reference: the DLL topic is described here: https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#dll-loading
