### ISSUE TITLE
RubyInstaller2 conflicts with MSYS1 based RubyInstaller

### ISSUE THREAD

**Issue by cosmo0920** [larskanis/rubyinstaller2#15]
[AppVeyor](https://www.appveyor.com/) is a Windows CI service.
It is working PowerShell based environment.

I've got the following result:

```log
c:/ruby24/bin/ruby extconf.rb
c:/ruby24/lib/ruby/site_ruby/ruby_installer/dll_directory.rb:75:in `add_dll_directory_winapi': AddDllDirectory failed (RubyInstaller::DllDirectory::WinApiError)
	from c:/ruby24/lib/ruby/site_ruby/ruby_installer/dll_directory.rb:46:in `initialize'
	from c:/ruby24/lib/ruby/site_ruby/ruby_installer/msys2_installation.rb:63:in `new'
	from c:/ruby24/lib/ruby/site_ruby/ruby_installer/msys2_installation.rb:63:in `enable_dll_search_paths'
	from c:/ruby24/lib/ruby/site_ruby/ruby_installer.rb:26:in `enable_dll_search_paths'
	from c:/ruby24/lib/ruby/2.4.0/rubygems/defaults/operating_system.rb:7:in `<top (required)>'
	from c:/ruby24/lib/ruby/2.4.0/rubygems.rb:1345:in `require'
	from c:/ruby24/lib/ruby/2.4.0/rubygems.rb:1345:in `<top (required)>'
	from <internal:gem_prelude>:4:in `require'
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
rake aborted!
```

https://ci.appveyor.com/project/cosmo0920/win32-api/build/47/job/ep9h2sw4g17ivb3g#L477

**Comment by larskanis** [comment]
This error is raised if the mingw directory does not exist. It should be `c:/msys64/mingw32/bin` on appveyor. It is probably caused by `%devkit64%\devkitvars.bat` , which sets `RI_DEVKIT` and due to the fact that RI2 considers `RI_DEVKIT` [as the root MSYS2 path](https://github.com/larskanis/rubyinstaller2/blob/master/lib/ruby_installer/msys2_installation.rb#L24) .

I think it is better to ignore a previous setting of RI_DEVKIT. There is no need for it. And the error message should contain the failed path.

Can you please try to delete the environment variable `set RI_DEVKIT=` before the RI2-part on appveyor?

**Comment by cosmo0920** [comment]
I want to use DevKit1 based Rubies and RI2 Rubies in the same rake task to create universal gem.
Can we use them there?

**Comment by larskanis** [comment]
A predefined `RI_DEVKIT` does [no longer break MSYS detection](https://github.com/larskanis/rubyinstaller2/commit/1cb33a41b680b4eafa1fa9b4142f4f6792450400) in RI2.

The use of MSYS1 and MSYS2 in one shell is difficult, because both toolsets contain the same commands in very different versions. You probably have to use either subshells with distinct MSYS1/2 activation or need to switch to MSYS2 for all ruby versions. In case of [rake-compiler-dock](https://github.com/rake-compiler/rake-compiler-dock) I choosed the latter way.

**Comment by larskanis** [comment]
Before the next [release to github](https://github.com/larskanis/rubyinstaller2/releases) , you can either `set RI_DEVKIT=` in front of the RI2-part on appveyor or download the latest [artifacts from appveyor](https://ci.appveyor.com/project/larskanis/rubyinstaller2/branch/master) .

**Comment by cosmo0920** [comment]
Thanks for explaining the root cause this problem.
I'd acheived to get success building MSYS1 and MSYS2 mixed gem with this commit: https://github.com/cosmo0920/win32-api/commit/b06f5c00fe79b4358c46a7c3f2b0666ca28d05b1

But I feel that this is not straightforward solution.

**Comment by larskanis** [comment]
If the running Ruby interpreter is RI2, then you could use:
```ruby
  ENV.delete('RI_DEVKIT')
  require "ruby_installer"
  RubyInstaller.enable_msys_apps
```
But this is bundled with the RubyInstaller2 and so far not available as a separate gem, so that other Ruby versions will fail to `require 'ruby_installer'` . So if your work-around works for you, then keep it.

**Comment by larskanis** [comment]
I think this issue is solved now.
