### ISSUE TITLE
readline library is broken

### ISSUE THREAD

**Issue by larskanis** [larskanis/rubyinstaller2#5]
Both readline-6.3 and readline-7.0 are broken on Windows. Therefore `irb` isn't fun to use. It's probably best to switch to rb-readline.gem, as the RubyInstaller does.

**Comment by MSP-Greg** [comment]
@larskanis 

I assume that readline-7.0 has been updated since the version of libreadline7.dll on my system is 03Feb.

It's working on my x64 builds with 2.5.0 (trunk); has about the same test failures as rb-readline.  irb seems to work also, although I haven't gone crazy using it (irb).  You may know how to test it better than I...
