### ISSUE TITLE
MSYS2 and pacman installation helper

### ISSUE THREAD

**Issue by larskanis** [larskanis/rubyinstaller2#9]
In the case that MSYS2 is required (for `gem install` , `rubydevkit` command, etc) we only print a [short download advice](https://github.com/larskanis/rubyinstaller2/blob/master/lib/ruby_installer.rb#L104-L105) , currently. The user needs to do the MSYS2 download and proper `pacman` runs by hand.

Maybe we could:
1. Start an interactive install process in case MSYS2 is required (while `gem install`)
2. Add a startmenu entry that opens an interactive install for MSYS2 and pacman apps.
3. Add a button on the very last installer page to open an interactive install for MSYS2

**Comment by Azolo** [comment]
I would say that the DevKit and/or the environment setup is the hardest part for almost every new user and is the source of most of the troubleshooting problems. So, the more automation the better, at least in my opinion.

Then I think of Ruby manager tools, `rbenv` has `ruby-build` and `rvm` has `autolibs`. Since on Windows we are installing a built package then may need an actual build environment afterwards, I think it would be ok to add a vendored gem that would handle setting up a build environment.

**Comment by larskanis** [comment]
MSYS2 installation is now an option at the finish page of the installer. It is also available as `rake install`. So option 3 of the list above is implemented now.
